print 'insert data into the incident table';
                                                                                                                                                                                                                                                                                            -- incident_id,
                                                                                                                                                                                                                                                                                            -- incident_code, 
                                                                                                                                                                                                                                                                                            -- incident_registered_date,
                                                                                                                                                                                                                                                                                            -- incident_number,
                                                                                                                                                                                                                                                                                            -- incident_reincident,
                                                                                                                                                                                                                                                                                            -- incident_reported_by,
                                                                                                                                                                                                                                                                                            -- incident_severity,
                                                                                                                                                                                                                                                                                            -- incident_treatment,
                                                                                                                                                                                                                                                                                            -- incident_detail_id,
                                                                                                                                                                                                                                                                                            -- incident_type_id,
                                                                                                                                                                                                                                                                                            -- personal_id
if(select count(*) from dbo.incident)=0
begin
	set identity_insert dbo.incident on;
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (1, 'ACC-01', '2017-06-27 11:56:44', 0, 0, 'admin', 'alta', 0, 1, 1,1);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (2, 'ENF-01', '2017-07-27 11:56:44', 0, 0, 'admin', 'baja', 0, 2, 2,2);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (3, 'INC-01', '2017-08-27 11:56:44', 0, 0, 'admin', 'media', 0, 3, 3,3);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (4, 'ACC-01', '2017-01-27 11:56:44', 0, 0, 'admin', 'alta', 0, 1, 1,1);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (5, 'ACC-01', '2017-02-27 11:56:44', 0, 0, 'admin', 'baja', 0, 3, 4,4);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (6, 'ACC-01', '2017-03-27 11:56:44', 0, 0, 'admin', 'baja', 0, 3, 5,5);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (7, 'ACC-01', '2017-04-27 11:56:44', 0, 0, 'admin', 'baja', 0, 3, 6,6);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (8, 'ACC-01', '2017-06-27 11:56:44', 0, 0, 'admin', 'baja', 0, 3, 7,7);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (9, 'ACC-01', '2017-05-27 11:56:44', 0, 0, 'admin', 'baja', 0, 3, 8,8);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (10, 'ACC-01', '2018-05-22 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 9,9);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (11, 'ACC-01', '2018-06-22 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 10,10);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (12, 'ACC-01', '2018-07-27 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 11,11);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (13, 'ACC-01', '2018-08-27 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 12,12);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (14, 'ACC-01', '2018-09-27 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 13,13);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (15, 'ACC-01', '2018-10-27 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 14,14);
	INSERT INTO dbo.incident (incident_id, incident_code, incident_registered_date, incident_number, incident_reincident, incident_reported_by, incident_severity, incident_treatment, incident_detail_id, incident_type_id, personal_id) VALUES (16, 'ACC-01', '2018-11-27 16:56:44', 0, 0, 'admin', 'baja', 0, 3, 15,15);
	set identity_insert dbo.incident off;
	print 'incident done';
end
-- End Insident
